### ISSUE TITLE
IllegalArgumentException: ChartId cannot be null or empty

### ISSUE THREAD

**Issue by alchemistmatt** [AddstarMC/QuickShop#1]
Load error with the latest release:
```
2018-03-04 18:14:18 [Server thread/ERROR]: Error occurred while enabling QuickShop v4.8.0-SNAPSHOT- (Is it up to date?)
java.lang.IllegalArgumentException: ChartId cannot be null or empty!
        at org.maxgamer.Metrics.bukkit.Metrics$CustomChart.<init>(Metrics.java:352) ~[?:?]
        at org.maxgamer.Metrics.bukkit.Metrics$MultiLineChart.<init>(Metrics.java:550) ~[?:?]
        at org.maxgamer.QuickShop.Metrics.ShopListener.<init>(ShopListener.java:22) ~[?:?]
        at org.maxgamer.QuickShop.QuickShop.onEnable(QuickShop.java:214) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2-96.jar:git-Spigot-4bd94dc-f4ca180]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2-96.jar:git-Spigot-4bd94dc-f4ca180]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2-96.jar:git-Spigot-4bd94dc-f4ca180]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2-96.jar:git-Spigot-4bd94dc-f4ca180]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2-96.jar:git-Spigot-4bd94dc-f4ca180]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2-96.jar:git-Spigot-4bd94dc-f4ca180]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2-96.jar:git-Spigot-4bd94dc-f4ca180]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2-96.jar:git-Spigot-4bd94dc-f4ca180]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2-96.jar:git-Spigot-4bd94dc-f4ca180]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2-96.jar:git-Spigot-4bd94dc-f4ca180]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

**Comment by alchemistmatt** [comment]
Fixed via 1631959af71e6
