### ISSUE TITLE
Paper 1.13 MySql error

### ISSUE THREAD

**Issue by alchemistmatt** [AddstarMC/QuickShop#2]
Error encountered while enabling QuickShop v4.8.2 on Paper 1.13.2 with MySql
```
database:
    mysql: true
    host: mysql
    port: 3306
   database: quickshop
    user: quickshop
    password: quickshop
```

2018-12-03 18:30:06 [Server thread/INFO]: Enabling QuickShop v4.8.2-SNAPSHOT-40
2018-12-03 18:30:06 [Server thread/INFO]: Hooking Vault
2018-12-03 18:30:06 [Server thread/INFO]: Starting item scheduler
2018-12-03 18:30:06 [Server thread/INFO]: Limit cfg found...
2018-12-03 18:30:06 [Server thread/INFO]: Limits.use: false
2018-12-03 18:30:06 [Server thread/INFO]: {quickshop=0, quickshop.vip=20}
2018-12-03 18:30:06 [Server thread/ERROR]: Error occurred while enabling QuickShop v4.8.2-SNAPSHOT-40 (Is it up to date?)
java.lang.NullPointerException: null
        at java.util.Hashtable.put(Hashtable.java:460) ~[?:1.8.0_191]
        at java.util.Properties.setProperty(Properties.java:166) ~[?:1.8.0_191]
        at com.mysql.jdbc.NonRegisteringDriver.parseURL(NonRegisteringDriver.java:808) ~[patched_1.13.2.jar:git-Paper-470]
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:321) ~[patched_1.13.2.jar:git-Paper-470]
        at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_191]
        at java.sql.DriverManager.getConnection(DriverManager.java:208) ~[?:1.8.0_191]
        at org.maxgamer.QuickShop.Database.MySQLCore.getConnection(MySQLCore.java:46) ~[?:?]
        at org.maxgamer.QuickShop.Database.Database.<init>(Database.java:26) ~[?:?]
        at org.maxgamer.QuickShop.QuickShop.setupDatabase(QuickShop.java:239) ~[?:?]
        at org.maxgamer.QuickShop.QuickShop.onEnable(QuickShop.java:180) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-470]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.2.jar:git-Paper-470]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-470]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-470]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-470]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.2.jar:git-Paper-470]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[patched_1.13.2.jar:git-Paper-470]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[patched_1.13.2.jar:git-Paper-470]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-470]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-470]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
2018-12-03 18:30:06 [Server thread/INFO]: Disabling QuickShop v4.8.2-SNAPSHOT-40
2018-12-03 18:30:06 [Server thread/ERROR]: Error occurred while disabling QuickShop v4.8.2-SNAPSHOT-40 (Is it up to date?)
java.lang.NullPointerException: null
        at org.maxgamer.QuickShop.QuickShop.onDisable(QuickShop.java:452) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256) ~[patched_1.13.2.jar:git-Paper-470]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359) ~[patched_1.13.2.jar:git-Paper-470]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437) ~[patched_1.13.2.jar:git-Paper-470]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) ~[patched_1.13.2.jar:git-Paper-470]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-470]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-470]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-470]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.2.jar:git-Paper-470]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[patched_1.13.2.jar:git-Paper-470]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[patched_1.13.2.jar:git-Paper-470]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-470]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-470]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by alchemistmatt** [comment]
With v4.8.2.40, after placing a chest on the ground and punching it with an item (for example a fish) it says `Enter how much you wish to trade one Raw Cod for in chat`
After typing a value like `16` in chat, a floating fish appears over the chest, but the quickShop sign does not appear (saying how much the fish is selling for).
Testing v4.8.2.42, I see `Enter how much you wish to trade one Raw Cod for in chat` but the floating item doesn't appear after typing a price (and no sign appears), and 1000 lines of an exception trace are logged to server.log
